# DO NOT EDIT. This file is generated by update.sh
{ fetchFromGitHub }: {

  version = "5.10.1";

  cmake = fetchFromGitHub {
    owner = "KitWare";
    repo = "CMake";
    rev = "31f835410efeea50acd43512eb9e5646a26ea177";
    hash = "sha256-3RAmxoX2zaKlg2yj3fTWMfBhj0TFNdVKQfJyG0epVg4=";
  };

  cmark = fetchFromGitHub {
    owner = "apple";
    repo = "swift-cmark";
    rev = "3bc2f3e25df0cecc5dc269f7ccae65d0f386f06a";
    hash = "sha256-GK2tFu49Sw8jJWJpxQerVFqsuUJwkAhRloa2/aUTYB8=";
  };

  curl = fetchFromGitHub {
    owner = "curl";
    repo = "curl";
    rev = "d755a5f7c009dd63a61b2c745180d8ba937cbfeb";
    hash = "sha256-2sAnQKWk67MNR2pFQGDN1mQ6re+A9we3oPkM6bZAmYw=";
  };

  icu = fetchFromGitHub {
    owner = "unicode-org";
    repo = "icu";
    rev = "0e7b4428866f3133b4abba2d932ee3faa708db1d";
    hash = "sha256-Pf8wbeWyWOqdHQbOoTsHMktinUxdc8eXWrOLCqZ0IJU=";
  };

  indexstore-db = fetchFromGitHub {
    owner = "apple";
    repo = "indexstore-db";
    rev = "89ec16c2ac1bb271614e734a2ee792224809eb20";
    hash = "sha256-2EIzEaVLHZ5vwO8skTaq9HoAaLuT9WFVLMgcgGYuVAk=";
  };

  libxml2 = fetchFromGitHub {
    owner = "gnome";
    repo = "libxml2";
    rev = "2b998a4ffbdfea04fc6a620721abc690a15743af";
    hash = "sha256-2SEzGhMeIHoHe9EKV6LgPLBXdmrxWWgnLYwUMZFWxNQ=";
  };

  llbuild = fetchFromGitHub {
    owner = "apple";
    repo = "swift-llbuild";
    rev = "fd7c2e0d9279edd023ced6b0a590f8407f5472f9";
    hash = "sha256-kUm8/+DWDBhuqU/kJBleqSl8/Vz478pMhx5QK2g7k0o=";
  };

  llvm-project = fetchFromGitHub {
    owner = "apple";
    repo = "llvm-project";
    rev = "e98989b1092ff3a72610a5be6251b010b06282f7";
    hash = "sha256-D+zZjLgnAFy6zBuUQwRI0VmDrgr2TQeNUnDbDtvtRZ4=";
  };

  ninja = fetchFromGitHub {
    owner = "ninja-build";
    repo = "ninja";
    rev = "2daa09ba270b0a43e1929d29b073348aa985dfaa";
    hash = "sha256-RT5u+TDvWxG5EVQEYj931EZyrHUSAqK73OKDAascAwA=";
  };

  sourcekit-lsp = fetchFromGitHub {
    owner = "apple";
    repo = "sourcekit-lsp";
    rev = "7e2d80cd12dfc168f4d9f444550461df1169bbd1";
    hash = "sha256-mMZ8zPkyoht0aSSnStIULWbLjowahdza9DQXboT1D0o=";
  };

  swift = fetchFromGitHub {
    owner = "apple";
    repo = "swift";
    rev = "0cbf541194159e0576548a0f2b9bf41bf16ef631";
    hash = "sha256-UK8yPwHu/sCvcuKKmBMCP9rGRJCZE3ct0ckdNw2BVbE=";
  };

  swift-argument-parser = fetchFromGitHub {
    owner = "apple";
    repo = "swift-argument-parser";
    rev = "8f4d2753f0e4778c76d5f05ad16c74f707390531";
    hash = "sha256-qEJ329hqQyQVxtHScD7qPmWW9ZDf9bX+4xgpDlX0w5A=";
  };

  swift-asn1 = fetchFromGitHub {
    owner = "apple";
    repo = "swift-asn1";
    rev = "12c24ff59d541e5ef15116095445ce72b85cd0c6";
    hash = "sha256-66NK8Qw7A6JAGeRDHODEhRP8yoCewYwK7zYc1uB1j5g=";
  };

  swift-atomics = fetchFromGitHub {
    owner = "apple";
    repo = "swift-atomics";
    rev = "919eb1d83e02121cdb434c7bfc1f0c66ef17febe";
    hash = "sha256-6fMm8q57/KUS+1xRKzCWO+a45tAxK6SKrhXwOuxhZas=";
  };

  swift-certificates = fetchFromGitHub {
    owner = "apple";
    repo = "swift-certificates";
    rev = "01d7664523af5c169f26038f1e5d444ce47ae5ff";
    hash = "sha256-n5dE5J8f7PAVoJkIpiKrrDvB0xIil5VwtzC2mx6vz80=";
  };

  swift-cmark-gfm = fetchFromGitHub {
    owner = "apple";
    repo = "swift-cmark";
    rev = "3bc2f3e25df0cecc5dc269f7ccae65d0f386f06a";
    hash = "sha256-GK2tFu49Sw8jJWJpxQerVFqsuUJwkAhRloa2/aUTYB8=";
  };

  swift-collections = fetchFromGitHub {
    owner = "apple";
    repo = "swift-collections";
    rev = "a902f1823a7ff3c9ab2fba0f992396b948eda307";
    hash = "sha256-2GcZXxwHpaxoN/ua6J4oEKNi1fCBpAox3nP13oXeooU=";
  };

  swift-corelibs-foundation = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-foundation";
    rev = "635aecde27a973cec77a6d99978673278b0c0b3e";
    hash = "sha256-izYpdCZaf3ktgz/k3pjmHJHH5BebdG7nj8l6vbuk+o0=";
  };

  swift-corelibs-libdispatch = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-libdispatch";
    rev = "9566a131de09a472790f7b69ae661326cdedf306";
    hash = "sha256-pta3wJj2LJ/lsYAWQpw0wSGLDMO41mN8Zbl78LUCaQo=";
  };

  swift-corelibs-xctest = fetchFromGitHub {
    owner = "apple";
    repo = "swift-corelibs-xctest";
    rev = "850c973eba78a24ec7921c72ee7bc3ffac91c02e";
    hash = "sha256-HgnVFYUuefCZKsOjXgt98ebMsLdMl0oXFXy2Pb2iUdw=";
  };

  swift-crypto = fetchFromGitHub {
    owner = "apple";
    repo = "swift-crypto";
    rev = "629f0b679d0fd0a6ae823d7f750b9ab032c00b80";
    hash = "sha256-lcB497b/T1bHShPrjNjHthrs76pDFpU+4uN0uW4tz+4=";
  };

  swift-docc = fetchFromGitHub {
    owner = "apple";
    repo = "swift-docc";
    rev = "baff176d26d935c104d0fea2ba9e3d97b333e25d";
    hash = "sha256-zgGahAanYI95nQZ+3zAYrs0h4APNamPrZfwF81k1si0=";
  };

  swift-docc-render-artifact = fetchFromGitHub {
    owner = "apple";
    repo = "swift-docc-render-artifact";
    rev = "843b62679b62350829a0574bc8fc532dc7c1312d";
    hash = "sha256-Ky9l6tzAxQOpcPFq2FeGnFUl8i59TifRBSHNaZg8wfw=";
  };

  swift-docc-symbolkit = fetchFromGitHub {
    owner = "apple";
    repo = "swift-docc-symbolkit";
    rev = "1d5aba8186fc648e17b30631b34043110ca8dd19";
    hash = "sha256-hAcoe57wE9gkPc1E/lXY41W+Eh3a7cUWfRv3Xi4rO2M=";
  };

  swift-driver = fetchFromGitHub {
    owner = "apple";
    repo = "swift-driver";
    rev = "b461fd4fc51be8e1f2a3f4a2184b664b8846b46f";
    hash = "sha256-Xaz9gZuOspDb+PB67d6tXfpcs+kkDCPSkhu+eIfrb0A=";
  };

  swift-experimental-string-processing = fetchFromGitHub {
    owner = "apple";
    repo = "swift-experimental-string-processing";
    rev = "d56f16a8ebc27d0f8e1c6270c83b1d9765e0f4a3";
    hash = "sha256-gv3xY9s6gdv0lpXH8RGfiLAvZWM7xVsUSLcqyb4rSeQ=";
  };

  swift-format = fetchFromGitHub {
    owner = "apple";
    repo = "swift-format";
    rev = "3191b8f3109730af449c6332d0b1ca6653b857a0";
    hash = "sha256-oYf9Qt0b/6G3+uQaoExQRKzgpi1RPYSSpZLfwhuRmF8=";
  };

  swift-installer-scripts = fetchFromGitHub {
    owner = "apple";
    repo = "swift-installer-scripts";
    rev = "bb3332b414166bfc0d2ca47d5b26b0e495711a70";
    hash = "sha256-qsMRzlrbBRo84tWGFnLJUCgac6p682l5NHXAjAv6120=";
  };

  swift-integration-tests = fetchFromGitHub {
    owner = "apple";
    repo = "swift-integration-tests";
    rev = "c1c3058ce09198c5f02a3acb444934faec9c9a93";
    hash = "sha256-PHO8rgxlK5VE2C7x8Bcw0Is6SgbaA9o2XBY/odEvdg4=";
  };

  swift-llvm-bindings = fetchFromGitHub {
    owner = "apple";
    repo = "swift-llvm-bindings";
    rev = "46c67a9c1018980b92a869ad58a5ac290e64b9e0";
    hash = "sha256-87taAyf52FdH0ERCbvZFqNvCHzeLdCS1rSXBh+mrfkI=";
  };

  swift-lmdb = fetchFromGitHub {
    owner = "apple";
    repo = "swift-lmdb";
    rev = "584941b1236b15bad74d8163785d389c028b1ad8";
    hash = "sha256-dZDN2pBOE0ZPtneQvEjF+AE4PDwbcaTausR2W4lg9Ss=";
  };

  swift-markdown = fetchFromGitHub {
    owner = "apple";
    repo = "swift-markdown";
    rev = "d91b618fb49f2b1b93f048efb833fa6867e1ef56";
    hash = "sha256-zntzy7N6QJjDC+avnazYkV18NW6FQbqDvWsBtqCjwP8=";
  };

  swift-nio = fetchFromGitHub {
    owner = "apple";
    repo = "swift-nio";
    rev = "1d425b0851ffa2695d488cce1d68df2539f42500";
    hash = "sha256-FscOA/S7on31QCR/MZFjg4ZB3FGJ+rdptZ6MRZJXexE=";
  };

  swift-nio-ssl = fetchFromGitHub {
    owner = "apple";
    repo = "swift-nio-ssl";
    rev = "2e74773972bd6254c41ceeda827f229bccbf1c0f";
    hash = "sha256-5QGkmkCOXhG3uOdf0bd3Fo1MFekB8/WcveBXGhtVZKo=";
  };

  swift-numerics = fetchFromGitHub {
    owner = "apple";
    repo = "swift-numerics";
    rev = "0a23770641f65a4de61daf5425a37ae32a3fd00d";
    hash = "sha256-wGIJ4hMxIBHy8mqmUGFWPR56wPFlI5qS4N7+nsFqLbs=";
  };

  swift-stress-tester = fetchFromGitHub {
    owner = "apple";
    repo = "swift-stress-tester";
    rev = "d330b3a99d0d8fbef025a3d8d4ef6f61a134f0c0";
    hash = "sha256-Ccx5UhGYyqLVt0b8Wu34z+X7dC8YW9IGJC4yN1ZRECk=";
  };

  swift-syntax = fetchFromGitHub {
    owner = "apple";
    repo = "swift-syntax";
    rev = "303e5c5c36d6a558407d364878df131c3546fad8";
    hash = "sha256-OcrOdlnLYpMxH5CGWNGbs5XW3gJaGgKWQqB9YtwmZeY=";
  };

  swift-system = fetchFromGitHub {
    owner = "apple";
    repo = "swift-system";
    rev = "836bc4557b74fe6d2660218d56e3ce96aff76574";
    hash = "sha256-p18QHzO+NtoY/WQzOD+PfD+bjqrIWsbeEbsJLPqEAhA=";
  };

  swift-tools-support-core = fetchFromGitHub {
    owner = "apple";
    repo = "swift-tools-support-core";
    rev = "90bdc2a157ebacc5d3de0c83e085d05d22ca5fa0";
    hash = "sha256-Pqy01AyDg7ZTyDM6lV69e6nhfhxwFTOhGFTfhcA1e9E=";
  };

  swift-xcode-playground-support = fetchFromGitHub {
    owner = "apple";
    repo = "swift-xcode-playground-support";
    rev = "bbba1ba704c37d1d0131bb7d6986a80ad8cb6d6c";
    hash = "sha256-esv5h1SLs/oy7hr4CwhnHufwlBxu2Q+gfbTYU/LlkyE=";
  };

  swiftpm = fetchFromGitHub {
    owner = "apple";
    repo = "swift-package-manager";
    rev = "54d135fb1fc8ef2041f1525e98d0ef14c23e9e64";
    hash = "sha256-yL/cPCt7pZ0XqbbxEnrbzM2X3EkU9klon7SzO2Z13SA=";
  };

  yams = fetchFromGitHub {
    owner = "jpsim";
    repo = "Yams";
    rev = "01835dc202670b5bb90d07f3eae41867e9ed29f6";
    hash = "sha256-5qxuCkmopm3uFcoYJKQA8ofW98f53H1gZaPiOh2DS4U=";
  };

  zlib = fetchFromGitHub {
    owner = "madler";
    repo = "zlib";
    rev = "09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851";
    hash = "sha256-eUuXV5zfy+fmiMNdWw5QCqDloBkaxy1tgi7by9nYHNA=";
  };

}
